import Head from 'next/head'
import FeaturedArticle from '../components/FeaturedArticle'
import SubscribeNow from '../components/SubscribeNow'
import TimeLine from '../components/TimeLine'
import { getTitle } from '../lib/constant'
import { getRecentContentList } from '../lib/service/content'
import DissolveHR from '../components/DissolveHR'

const count = 3

export default function Home(props) {
  return (
    <div className={' bg-iceburg-4'}>
      <Head>
        <title>{getTitle('home')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedArticle title={'新笔'} articles={props.articles} pageSize={count} fillBlank={true} />
      <TimeLine title='记录'/>
      <DissolveHR />
      <SubscribeNow />
    </div>
  )
}

// This function gets called at build time
export async function getStaticProps() {
  const articles = await getRecentContentList(count, 0)
  return {
    props: {
      articles: articles,
    },
    revalidate: 3000,
  }
}